routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Http\Request;
use App\User;
// use Auth;

Route::get('/', function () {
    return view('welcome');
});

Route::group(['namespace' => 'Admin'] , function(){

	Auth::routes(['register' => false]);
});

//Admin Routes
Route::group(['middleware' => 'Admin', 'namespace' => 'Admin' ,'prefix' => 'admin'] , function(){

	Route::get('dashboard' , 'HomeController@dashboard')->name('dashboard');

	Route::resource('team', 'TeamController', ['as' => 'admin']);
	Route::resource('skill', 'SkillController', ['as' => 'admin']);
	Route::resource('school', 'SchoolController', ['as' => 'admin']);
	Route::resource('coach', 'CoachController');
	Route::resource('member', 'MemberController');

	//Admins
	Route::get('admins', 'AdminController@show')->name('admins');
	Route::get('admin/form', 'AdminController@newAdmin')->name('newAdmin');
	Route::post('admin/new/create', 'AdminController@store')->name('createNewAdmin');
	Route::get('admin/form/{id}', 'AdminController@form')->name('editAdmin');
	Route::put('admin/update/{id}', 'AdminController@update')->name('updateAdmin');
	Route::get('admin/delete/{id}', 'AdminController@destroy')->name('deleteAdmin');

	//Member
	Route::get('member/delete/{id}', 'MemberController@deleteMember')->name('memberDelete');
	Route::get('coach/delete/{id}', 'CoachController@deleteCoach')->name('coachDelete');

	//Clinics
	Route::get('clinics', 'HomeController@clinics')->name('clinics');

});



//Auth routes
Route::group(['middleware' => ['auth']], function () {
	//Tickets
	Route::get('tickets' , 'TicketController@index')->name('tickets');
	Route::get('tickets/new' , 'TicketController@newTicketForm')->name('newTicketForm');
	Route::post('tickets/new/create' , 'TicketController@createTicket')->name('createTicket');
	Route::get('tickets/close/{id}' , 'TicketController@closeTicket')->name('closeTicket');
	Route::get('tickets/detail/{id}' , 'TicketController@ticketDetail')->name('ticketDetail');
	Route::get('tickets/delete/{id}' , 'TicketController@ticketDelete')->name('ticketDelete');
	
	
	//Comments
	Route::post('comment/new', 'CommentController@createComment')->name('createComment');
	
});

//Coach Routes
Route::group(['middleware' => 'Coach' , 'prefix' => 'coach' , 'namespace' => 'Coach'] , function(){
	Route::get('/dashboard' , 'DashboardController@index')->name('coach.dashboard');
	Route::get('/profile' , 'DashboardController@profile')->name('coach.profile');
	Route::post('/profile/update' , 'DashboardController@profileUpdate')->name('coach.profile.update');

	Route::get('schedule-clinic' , 'ClinicController@index')->name('coach.clinic');
	Route::get('schedule-clinic/clinic/update/{id}' , 'ClinicController@updateClinic')->name('updateClinic');
	Route::get('schedule-clinic/{id}/show' , 'ClinicController@show')->name('coach.clinic.show');
	Route::post('schedule-clinic/store' , 'ClinicController@store')->name('coach.clinic.store');
	Route::get('schedule-clinic/{id}/edit' , 'ClinicController@edit')->name('coach.clinic.edit');
	Route::put('schedule-clinic/update/{id}' , 'ClinicController@update')->name('coach.clinic.update');
	Route::get('schedule-clinic/delete/{id}' , 'ClinicController@delete')->name('coach.clinic.delete');
	Route::get('summary' , 'DashboardController@coachSummary')->name('coach.summary');

	Route::get('clinic/registers/{id}' , 'ClinicController@clinicEnroll')->name('coach.clinic.enroll');
	Route::post('uniformrequirements' , 'DashboardController@setUniformRequirements')->name('uniform.requirements');

	Route::get('/clinics/all' , 'ClinicController@getAllClinics')->name('coach.clinics.all');
	
});
Route::post('clinic/location/new' , 'ClinicLocationController@store')->name('clinic.location.store');

//Member Routes
Route::group(['middleware' => 'Member' , 'prefix' => 'member' , 'namespace' => 'Member'] , function(){

    Route::get('/dashboard' , 'DashboardController@index')->name('member.dashboard');
    Route::get('/enrolled/clinics' , 'DashboardController@enrolled_clinic');
	Route::get('/profile', 'ProfileController@index')->name('member.profile');
	Route::post('/profile/update', 'ProfileController@profileUpdate')->name('member.profile.update');
	// Route::get('schedule/clinic' , 'DashboardController@scheduleClinic')->name('member.schedule.clinic');

});



// Route::post('/member/login' , 'Admin\Auth\LoginController@login')->name('login.attempt');

Route::group(['middleware' => 'guest'], function() {
	Route::get('register/member' , 'RegisterController@memberRegisterForm')->name('member.register.form');
	Route::post('register/member/store' , 'RegisterController@memberStore')->name('member.register.store');
	Route::get('register/coach' , 'RegisterController@coachRegisterForm')->name('coach.register.form');
	// Route::view('user/login' , 'member.login')->name('user.login');
});
	Route::post('register/school/coach' , 'RegisterController@school')->name('coach.school.store');


Route::view('about' , 'pages.about' )->name('about');
Route::get('/' , 'HomeController@index')->name('home');

Route::get('/clinics' , 'ClinicController@index')->name('clinic.index');
Route::get('clinics/search' , 'ClinicController@searchCLinics')->name('clinicSearch');
Route::get('clinic/detail/{id}', 'ClinicController@detail')->name('clinic.detail');
Route::get('clinic/enrolled/detail/{id}', 'ClinicController@enrolledDetail')->name('clinic.enrolled.detail');
Route::get('clinic/enroll/{id}' , 'ClinicController@enroll')->name('enroll.index');
Route::post('clinic/enroll/update/{id}' , 'ClinicController@updateClinic')->name('clinic.enroll.update');

Route::get('contact-us' , 'ContactController@index')->name('contact');

Route::get('/pay','PaymentController@pay')->name('pay');
Route::post('/dopay/online', 'PaymentController@handleonlinepay')->name('dopay.online');

Route::get('/waiverA',function(){

    return view('waivers.waiverA');
});

Route::get('/waiverB','WaiverController@waiverB');
Route::post('/waiverB/submit','WaiverController@waiverB_send');
Route::get('/waiver/view/{id}','WaiverController@waiver_view');
Route::get('/waiverA','WaiverController@waiverA');
Route::post('/waiver/submit','WaiverController@WaiverA_submit');

Route::post('/notes/new','Member\DashboardController@notes');

Route::get('enrollments/paid', [
    'uses' => 'Coach\DashboardController@paidEnrollments',
    'as' => 'paid-enrollments'
]);

Route::get('enrollments/unpaid', [
    'uses' => 'Coach\DashboardController@unPaidEnrollments',
    'as' => 'unpaid-enrollments'
]);

Route::get('mailable', function () {
	// Mail::to(Auth::user())->send(new NewComment($ticket));
	
	$ticket = App\Ticket::find(18);
	$clinic = App\Clinic::find(7);

	// return new App\Mail\newUserRegistration();
	// return new App\Mail\clinicEnrollment($clinic);
	return new App\Mail\PasswordResetConfirmation();
});

Route::get('/test', function(Request $request) {
	return Auth::user();
	
	
	// return Auth::user()->email;
	// return 2 + 1;
	// return $request;
	// return App\Clinic::find(1)->with('clinicDetails')->get();
	// return Auth::user();
	// return view('auth.passwords.reset');
});

Route::get('coach/school/detail', 'Coach\DashboardController@getSchool');

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/admin/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8" />
        <title>@yield('title')</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <!-- App favicon -->
        <link rel="shortcut icon" href="/assets/images/icon.png">
        <!-- Plugins css -->
        @yield('top-style')
        <link href="/assets/libs/flatpickr/flatpickr.min.css" rel="stylesheet" type="text/css" />
        <!-- App css -->
        <link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/css/app.min.css" rel="stylesheet" type="text/css" />
        @yield('style')
        <style>
           hr{
            border-top: 1px dotted #8c8b8b;
            margin: 20px 0 20px 0;
            }
        </style>
    </head>
    <body>
        <!-- Begin page -->
        <div id="wrapper">
            <!-- Topbar Start -->
            <div class="navbar-custom">
                <ul class="list-unstyled topnav-menu float-right mb-0">
                    {{-- <li class="dropdown notification-list">
                        <a class="nav-link dropdown-toggle  waves-effect waves-light" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                            <i class="fe-bell noti-icon"></i>
                            <span class="badge badge-danger rounded-circle noti-icon-badge">{{ count(Auth::user()->unreadNotifications) }}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-lg">
                            <!-- item-->
                            <div class="dropdown-item noti-title">
                                <h5 class="m-0">
                                    <span class="float-right">
                                    </span>Notification
                                </h5>
                            </div>
                            <div class="slimscroll noti-scroll">
                                @forelse (Auth::user()->unreadNotifications as $notification) 
                                <a href="{{ $notification->data['route'] }}" class="dropdown-item notify-item">
                                    <p class="notify-details">{{ $notification->data['subject'] }}
                                        
                                        <small class="text-muted">{{ \Carbon\Carbon::parse($notification->created_at)->diffForHumans(NOW() , true) }}</small>
                                    </p>
                                </a>
                                @empty
                                @endforelse
                            </div>
                        </div>
                    </li> --}}
                    <li class="dropdown notification-list">
                        <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                            <img src="{{ asset('uploads/profile/admin.png') }}" alt="user-image" class="rounded-circle">
                            <span class="pro-user-name ml-1">
                                {{ Auth::user()->first_name . ' ' . Auth::user()->last_name }} <i class="mdi mdi-chevron-down"></i>
                            </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                            <!-- item-->
                            <div class="dropdown-header noti-title">
                                <h6 class="text-overflow m-0">Welcome !</h6>
                            </div>
                            <!-- item-->
                            {{-- <a href="{{ route('profile') }}" class="dropdown-item notify-item">
                                <i class="fe-user"></i>
                                <span>My Profile</span>
                            </a> --}}
                            <!-- item-->
                            {{-- <a href="{{ route('change.password') }}" class="dropdown-item notify-item">
                                <i class="fe-settings"></i>
                                <span>Change Password</span>
                            </a> --}}
                            <div class="dropdown-divider"></div>
                            <!-- item-->
                            <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();" class="dropdown-item notify-item">
                                <i class="fe-log-out"></i>
                                <span>Logout</span>
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                </ul>
                <!-- LOGO -->
                <div class="logo-box">
                    <a href="/" class="logo text-center">
                        <span class="logo-lg">
                            <img src="/assets/images/logo-light.png" alt="" height="50">
                            <!-- <span class="logo-lg-text-light">UBold</span> -->
                        </span>
                        <span class="logo-sm">
                            <!-- <span class="logo-sm-text-dark">U</span> -->
                            <img src="/assets/images/logo-light.png" alt="" height="50">
                        </span>
                    </a>
                </div>
                <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
                    <li>
                        <button class="button-menu-mobile waves-effect waves-light">
                            <i class="fe-menu"></i>
                        </button>
                    </li>
                </ul>
            </div>
            <!-- end Topbar -->
            <!-- ========== Left Sidebar Start ========== -->
            <div class="left-side-menu">
                <div class="slimscroll-menu">
                    <!--- Sidemenu -->
                    <div id="sidebar-menu">
                        <ul class="metismenu" id="side-menu">
                            <li class="menu-title">Navigation</li>
                            <li>
                                <a href="{{ route('dashboard') }}">
                                    <i class="fe-airplay"></i>
                                    <span> Dashboards </span>
                                </a>
                            </li>
                            <li>
                                <a href="{{ route('tickets') }}">
                                    <i class="fe-pocket"></i>
                                    <span>Tickets</span>
                                </a>
                            </li>
                            <li>
                                <a href="javascript: void(0);">
                                    <i class="fe-pocket"></i>
                                    <span> Team Type </span>
                                    <span class="menu-arrow"></span>
                                </a>
                                <ul class="nav-second-level" aria-expanded="false">
                                    <li>
                                        <a href="{{ route('admin.team.index') }}">Team Type</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="javascript: void(0);">
                                    <i class="fe-pocket"></i>
                                    <span> Skill </span>
                                    <span class="menu-arrow"></span>
                                </a>
                                <ul class="nav-second-level" aria-expanded="false">
                                    <li>
                                        <a href="{{ route('admin.skill.index') }}">Skills</a>
                                    </li>
                                </ul>
                            </li>
                             <li>
                                <a href="javascript: void(0);">
                                    <i class="fe-pocket"></i>
                                    <span> Schools </span>
                                    <span class="menu-arrow"></span>
                                </a>
                                <ul class="nav-second-level" aria-expanded="false">
                                    <li>
                                        <a href="{{ route('admin.school.index') }}">Schools</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="javascript: void(0);">
                                    <i class="fe-pocket"></i>
                                    <span> Coaches </span>
                                    <span class="menu-arrow"></span>
                                </a>
                                <ul class="nav-second-level" aria-expanded="false">
                                    <li>
                                        <a href="{{ route('coach.index') }}">Coaches</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="javascript: void(0);">
                                    <i class="fe-pocket"></i>
                                    <span> Admins </span>
                                    <span class="menu-arrow"></span>
                                </a>
                                <ul class="nav-second-level" aria-expanded="false">
                                    <li>
                                        <a href="{{ route('admins') }}">Admins</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="javascript: void(0);">
                                    <i class="fe-pocket"></i>
                                    <span> Members </span>
                                    <span class="menu-arrow"></span>
                                </a>
                                <ul class="nav-second-level" aria-expanded="false">
                                    <li>
                                        <a href="{{ route('member.index') }}">Members</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <!-- End Sidebar -->
                    <div class="clearfix"></div>
                </div>
                <!-- Sidebar -left -->
            </div>
            @yield('mainContent')
</div>
        </div>
        <!-- END wrapper -->
        <!-- Right bar overlay-->
        <div class="rightbar-overlay"></div>
        <!-- Vendor js -->
        <script src="/assets/js/vendor.min.js"></script>
        <script>
            $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
        </script>
        @yield('script')
        <!-- App js-->
        <script src="/assets/js/app.min.js"></script>
    </body>

</html>