routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Http\Request;
use App\User;
// use Auth;

Route::get('/', function () {
    return view('welcome');
});

Route::group(['namespace' => 'Admin'] , function(){

	Auth::routes(['register' => false]);
});

//Admin Routes
Route::group(['middleware' => 'Admin', 'namespace' => 'Admin' ,'prefix' => 'admin'] , function(){

	Route::get('dashboard' , 'HomeController@dashboard')->name('dashboard');

	Route::resource('team', 'TeamController', ['as' => 'admin']);
	Route::resource('skill', 'SkillController', ['as' => 'admin']);
	Route::resource('school', 'SchoolController', ['as' => 'admin']);
	Route::resource('coach', 'CoachController');
	Route::resource('member', 'MemberController');

	//Admins
	Route::get('admins', 'AdminController@show')->name('admins');
	Route::get('admin/form', 'AdminController@newAdmin')->name('newAdmin');
	Route::post('admin/new/create', 'AdminController@store')->name('createNewAdmin');
	Route::get('admin/form/{id}', 'AdminController@form')->name('editAdmin');
	Route::put('admin/update/{id}', 'AdminController@update')->name('updateAdmin');
	Route::get('admin/delete/{id}', 'AdminController@destroy')->name('deleteAdmin');

	//Member
	Route::get('member/delete/{id}', 'MemberController@deleteMember')->name('memberDelete');
	Route::get('coach/delete/{id}', 'CoachController@deleteCoach')->name('coachDelete');

	//Clinics
	Route::get('clinics', 'HomeController@clinics')->name('clinics');

});



//Auth routes
Route::group(['middleware' => ['auth']], function () {
	//Tickets
	Route::get('tickets' , 'TicketController@index')->name('tickets');
	Route::get('tickets/new' , 'TicketController@newTicketForm')->name('newTicketForm');
	Route::post('tickets/new/create' , 'TicketController@createTicket')->name('createTicket');
	Route::get('tickets/close/{id}' , 'TicketController@closeTicket')->name('closeTicket');
	Route::get('tickets/detail/{id}' , 'TicketController@ticketDetail')->name('ticketDetail');
	Route::get('tickets/delete/{id}' , 'TicketController@ticketDelete')->name('ticketDelete');
	
	
	//Comments
	Route::post('comment/new', 'CommentController@createComment')->name('createComment');
	
});

//Coach Routes
Route::group(['middleware' => 'Coach' , 'prefix' => 'coach' , 'namespace' => 'Coach'] , function(){
	Route::get('/dashboard' , 'DashboardController@index')->name('coach.dashboard');
	Route::get('/profile' , 'DashboardController@profile')->name('coach.profile');
	Route::post('/profile/update' , 'DashboardController@profileUpdate')->name('coach.profile.update');

	Route::get('schedule-clinic' , 'ClinicController@index')->name('coach.clinic');
	Route::get('schedule-clinic/clinic/update/{id}' , 'ClinicController@updateClinic')->name('updateClinic');
	Route::get('schedule-clinic/{id}/show' , 'ClinicController@show')->name('coach.clinic.show');
	Route::post('schedule-clinic/store' , 'ClinicController@store')->name('coach.clinic.store');
	Route::get('schedule-clinic/{id}/edit' , 'ClinicController@edit')->name('coach.clinic.edit');
	Route::put('schedule-clinic/update/{id}' , 'ClinicController@update')->name('coach.clinic.update');
	Route::get('schedule-clinic/delete/{id}' , 'ClinicController@delete')->name('coach.clinic.delete');
	Route::get('summary' , 'DashboardController@coachSummary')->name('coach.summary');

	Route::get('clinic/registers/{id}' , 'ClinicController@clinicEnroll')->name('coach.clinic.enroll');
	Route::post('uniformrequirements' , 'DashboardController@setUniformRequirements')->name('uniform.requirements');

	Route::get('/clinics/all' , 'ClinicController@getAllClinics')->name('coach.clinics.all');
	
});
Route::post('clinic/location/new' , 'ClinicLocationController@store')->name('clinic.location.store');

//Member Routes
Route::group(['middleware' => 'Member' , 'prefix' => 'member' , 'namespace' => 'Member'] , function(){

    Route::get('/dashboard' , 'DashboardController@index')->name('member.dashboard');
    Route::get('/enrolled/clinics' , 'DashboardController@enrolled_clinic');
	Route::get('/profile', 'ProfileController@index')->name('member.profile');
	Route::post('/profile/update', 'ProfileController@profileUpdate')->name('member.profile.update');
	// Route::get('schedule/clinic' , 'DashboardController@scheduleClinic')->name('member.schedule.clinic');

});



// Route::post('/member/login' , 'Admin\Auth\LoginController@login')->name('login.attempt');

Route::group(['middleware' => 'guest'], function() {
	Route::get('register/member' , 'RegisterController@memberRegisterForm')->name('member.register.form');
	Route::post('register/member/store' , 'RegisterController@memberStore')->name('member.register.store');
	Route::get('register/coach' , 'RegisterController@coachRegisterForm')->name('coach.register.form');
	// Route::view('user/login' , 'member.login')->name('user.login');
});
	Route::post('register/school/coach' , 'RegisterController@school')->name('coach.school.store');


Route::view('about' , 'pages.about' )->name('about');
Route::get('/' , 'HomeController@index')->name('home');

Route::get('/clinics' , 'ClinicController@index')->name('clinic.index');
Route::get('clinics/search' , 'ClinicController@searchCLinics')->name('clinicSearch');
Route::get('clinic/detail/{id}', 'ClinicController@detail')->name('clinic.detail');
Route::get('clinic/enrolled/detail/{id}', 'ClinicController@enrolledDetail')->name('clinic.enrolled.detail');
Route::get('clinic/enroll/{id}' , 'ClinicController@enroll')->name('enroll.index');
Route::post('clinic/enroll/update/{id}' , 'ClinicController@updateClinic')->name('clinic.enroll.update');

Route::get('contact-us' , 'ContactController@index')->name('contact');

Route::get('/pay','PaymentController@pay')->name('pay');
Route::post('/dopay/online', 'PaymentController@handleonlinepay')->name('dopay.online');

Route::get('/waiverA',function(){

    return view('waivers.waiverA');
});

Route::get('/waiverB','WaiverController@waiverB');
Route::post('/waiverB/submit','WaiverController@waiverB_send');
Route::get('/waiver/view/{id}','WaiverController@waiver_view');
Route::get('/waiverA','WaiverController@waiverA');
Route::post('/waiver/submit','WaiverController@WaiverA_submit');

Route::post('/notes/new','Member\DashboardController@notes');

Route::get('enrollments/paid', [
    'uses' => 'Coach\DashboardController@paidEnrollments',
    'as' => 'paid-enrollments'
]);

Route::get('enrollments/unpaid', [
    'uses' => 'Coach\DashboardController@unPaidEnrollments',
    'as' => 'unpaid-enrollments'
]);

Route::get('mailable', function () {
	// Mail::to(Auth::user())->send(new NewComment($ticket));
	
	$ticket = App\Ticket::find(18);
	$clinic = App\Clinic::find(7);

	// return new App\Mail\newUserRegistration();
	// return new App\Mail\clinicEnrollment($clinic);
	return new App\Mail\PasswordResetConfirmation();
});

Route::get('/test', function(Request $request) {
	return Auth::user();
	
	
	// return Auth::user()->email;
	// return 2 + 1;
	// return $request;
	// return App\Clinic::find(1)->with('clinicDetails')->get();
	// return Auth::user();
	// return view('auth.passwords.reset');
});

Route::get('coach/school/detail', 'Coach\DashboardController@getSchool');

app/Skill.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Skill extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Admin/SkillController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Skill;
use Auth;

class SkillController extends Controller
{
    public function index()
    {
        $skills = Skill::get();
        return view('admin.skill.index' , compact('skills'));
    }

    public function create()
    {
        return view('admin.skill.update');
    }

    public function store(Request $request)
    {
        $this->validate(request(), [
                'title' => 'required|unique:skills',
            ]);

        $skill = Skill::create([
                'user_id' 		=> Auth::id(),
                'title' 		=> $request->title,
                'slug' 			=> createSlug($request->title , 'skills'),
                'description' 	=> $request->description,
            ]);

        return redirect()->to(route('admin.skill.index'))->with(['msg' => 'skill Successfully create.']);
    }

    public function edit($id)
    {
        $row = Skill::find($id);
        return view('admin.skill.update' , compact( 'row'));
    }

    public function update(Request $request , $id)
    {
    	$row = Skill::find($id);

    	$slug  = $row->slug;

    	if ($request->title != $row->title) {
	        $this->validate(request(), [
	                'title' => 'required',
	            ]);
	        $slug = createSlug($request->title , 'skills');
    	}


        $row->update([
            'user_id' 		=> Auth::id(),
            'title' 		=> $request->title,
            'slug' 			=> $slug,
            'description' 	=> $request->description,
        ]);

        return redirect()->to(route('admin.skill.index'))->with(['msg' => 'Skill Successfully updated.']);
    }

    public function destroy($id)
    {
        Skill::where('id' , $id)->delete();
        return response()->json(['status' => TRUE]);
    }
}

resources/views/admin/skill/index.blade.php
@extends('admin.layouts.master')
@section('title' , 'Skills')

@section('mainContent')

    <div class="content-page">
        <div class="content">

            <!-- Start Content-->
            <div class="container-fluid">
                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box">
                            <div class="page-title-right">
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                                    <li class="breadcrumb-item active">Skills</li>
                                </ol>
                            </div>
                            <h4 class="page-title">Skills</h4>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">

                                <div class="row mb-2">
                                    <div class="col-lg-8">
                                       <h4 class="header-title">Skills</h4>
                                    </div>
                                    <div class="col-lg-4">
                                        <div class="text-lg-right">
                                            <a href="{{ route('admin.skill.create') }}" class="btn btn-primary waves-effect waves-light"><i class="mdi mdi-basket mr-1"></i> Add New Skill</a>
                                        </div>
                                    </div><!-- end col-->
                                </div>

                                <table id="scroll-horizontal-datatable" class="table w-100 nowrap">
                                    <thead>
                                        <tr>
                                            <th>Title</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($skills as $skill)
                                          <tr>
                                            <td>{{ $skill->title }}</td>
                                            <td>
                                                <a href="{{ Route('admin.skill.edit' , $skill->id) }}" class="btn btn-info waves-effect waves-light btn-xs" title="Edit details"><i class="mdi mdi-square-edit-outline"></i></a>
                                                <a href="{{ Route('admin.skill.destroy' , $skill->id) }}" class="singleDelete btn btn-danger waves-effect waves-light btn-xs" title="Delete"><i class="mdi mdi-close"></i></a>
                                            </td>
                                        </tr>
                                        @empty
                                        @endforelse
                                    </tbody>
                                </table>

                            </div> <!-- end card body-->
                        </div> <!-- end card -->
                    </div><!-- end col-->
                </div>
                <!-- end row-->

            </div> <!-- container -->

        </div> <!-- content -->

       

    </div>


@stop

@section('style')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
<link href="/assets/libs/sweetalert2/sweetalert2.min.css" rel="stylesheet" type="text/css" />
@endsection

@section('script')
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
<script src="/assets/js/pages/datatables.init.js"></script>
<script src="/assets/libs/sweetalert2/sweetalert2.min.js"></script>
<script src="/assets/app/indexMaster.js"></script>
@endsection

resources/views/admin/skill/update.blade.php
@extends('admin.layouts.master')

@section('title' , 'Create / update Skill')

@section('mainContent')

@php
    if (isset($row->id)) {
       $action = Route('admin.skill.update' , $row->id);
    }else{
        $action = Route('admin.skill.store');
    }
@endphp

   <div class="content-page">
<div class="content">
    <!-- Start Content-->
    <div class="container-fluid">
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('admin.skill.index') }}">Teams</a></li>
                                <li class="breadcrumb-item active">Create / Update Skill</li>
                            </ol>
                        </div>
                        <h4 class="page-title">Create / Update Skill</h4>
                    </div>
                </div>
            </div>
            <!-- end page title -->
        </div>
        <!-- end row -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="header-title">Fill Out Your Skill Information</h4>

                        <hr>

                        <div class="clearfix"></div>
                        <div class="row">
                    		<div class="col-12 text-center">
                    			<div class="form-group">
                        			<h3>General Information</h3>
                    			</div>
		                    </div>
		                </div>

                        <form  method="post" action="{{ $action }}" id="eventForm" enctype="multipart/form-data" >

					    @csrf
                        @isset ($row->id)
                            @method('PUT')
                        @endisset
                        	<div class="row">
                    			<div class="col-8 m-auto">
                                    <div class="form-row">
                                        <div class="form-group col-md-12">
                                            <label for="title" class="col-form-label">Title</label>
                                            <input type="text" name="title" id="title" class="form-control @error('title') is-invalid @enderror" required value="{{ isset($row->title)? $row->title : old('title') }}">
                                             @error('title')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-row">
                                        <div class="form-group col-md-12">
                                            <label for="description" class="col-form-label">Description</label>
                                            <textarea name="description" id="description" class="form-control @error('description') is-invalid @enderror" cols="30" rows="10">{{ isset($row->description)? $row->description : old('description') }}</textarea>

                                             @error('description')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                    </div>
                                    
                                    <hr>

                                    <div class="form-group mb-0">
                                        <div class="custom-control custom-checkbox">
                                             <a href="{{ route('admin.skill.index') }}" class="btn btn-secondary  waves-effect waves-light">Cancel</a>
                                             <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                                        </div>
                                    </div>


								</div> <!-- end card-body -->
                        	</div>
                        </form>
                	</div>
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>
        <!-- end row -->


    </div> <!-- container -->

    </div> <!-- content -->


@stop

@section('top-style')
@stop

@section('style')

@endsection

@section('script')
@endsection