routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Http\Request;
use App\User;
// use Auth;

Route::get('/', function () {
    return view('welcome');
});

Route::group(['namespace' => 'Admin'] , function(){

	Auth::routes(['register' => false]);
});

//Admin Routes
Route::group(['middleware' => 'Admin', 'namespace' => 'Admin' ,'prefix' => 'admin'] , function(){

	Route::get('dashboard' , 'HomeController@dashboard')->name('dashboard');

	Route::resource('team', 'TeamController', ['as' => 'admin']);
	Route::resource('skill', 'SkillController', ['as' => 'admin']);
	Route::resource('school', 'SchoolController', ['as' => 'admin']);
	Route::resource('coach', 'CoachController');
	Route::resource('member', 'MemberController');

	//Admins
	Route::get('admins', 'AdminController@show')->name('admins');
	Route::get('admin/form', 'AdminController@newAdmin')->name('newAdmin');
	Route::post('admin/new/create', 'AdminController@store')->name('createNewAdmin');
	Route::get('admin/form/{id}', 'AdminController@form')->name('editAdmin');
	Route::put('admin/update/{id}', 'AdminController@update')->name('updateAdmin');
	Route::get('admin/delete/{id}', 'AdminController@destroy')->name('deleteAdmin');

	//Member
	Route::get('member/delete/{id}', 'MemberController@deleteMember')->name('memberDelete');
	Route::get('coach/delete/{id}', 'CoachController@deleteCoach')->name('coachDelete');

	//Clinics
	Route::get('clinics', 'HomeController@clinics')->name('clinics');

});



//Auth routes
Route::group(['middleware' => ['auth']], function () {
	//Tickets
	Route::get('tickets' , 'TicketController@index')->name('tickets');
	Route::get('tickets/new' , 'TicketController@newTicketForm')->name('newTicketForm');
	Route::post('tickets/new/create' , 'TicketController@createTicket')->name('createTicket');
	Route::get('tickets/close/{id}' , 'TicketController@closeTicket')->name('closeTicket');
	Route::get('tickets/detail/{id}' , 'TicketController@ticketDetail')->name('ticketDetail');
	Route::get('tickets/delete/{id}' , 'TicketController@ticketDelete')->name('ticketDelete');
	
	
	//Comments
	Route::post('comment/new', 'CommentController@createComment')->name('createComment');
	
});

//Coach Routes
Route::group(['middleware' => 'Coach' , 'prefix' => 'coach' , 'namespace' => 'Coach'] , function(){
	Route::get('/dashboard' , 'DashboardController@index')->name('coach.dashboard');
	Route::get('/profile' , 'DashboardController@profile')->name('coach.profile');
	Route::post('/profile/update' , 'DashboardController@profileUpdate')->name('coach.profile.update');

	Route::get('schedule-clinic' , 'ClinicController@index')->name('coach.clinic');
	Route::get('schedule-clinic/clinic/update/{id}' , 'ClinicController@updateClinic')->name('updateClinic');
	Route::get('schedule-clinic/{id}/show' , 'ClinicController@show')->name('coach.clinic.show');
	Route::post('schedule-clinic/store' , 'ClinicController@store')->name('coach.clinic.store');
	Route::get('schedule-clinic/{id}/edit' , 'ClinicController@edit')->name('coach.clinic.edit');
	Route::put('schedule-clinic/update/{id}' , 'ClinicController@update')->name('coach.clinic.update');
	Route::get('schedule-clinic/delete/{id}' , 'ClinicController@delete')->name('coach.clinic.delete');
	Route::get('summary' , 'DashboardController@coachSummary')->name('coach.summary');

	Route::get('clinic/registers/{id}' , 'ClinicController@clinicEnroll')->name('coach.clinic.enroll');
	Route::post('uniformrequirements' , 'DashboardController@setUniformRequirements')->name('uniform.requirements');

	Route::get('/clinics/all' , 'ClinicController@getAllClinics')->name('coach.clinics.all');
	
});
Route::post('clinic/location/new' , 'ClinicLocationController@store')->name('clinic.location.store');

//Member Routes
Route::group(['middleware' => 'Member' , 'prefix' => 'member' , 'namespace' => 'Member'] , function(){

    Route::get('/dashboard' , 'DashboardController@index')->name('member.dashboard');
    Route::get('/enrolled/clinics' , 'DashboardController@enrolled_clinic');
	Route::get('/profile', 'ProfileController@index')->name('member.profile');
	Route::post('/profile/update', 'ProfileController@profileUpdate')->name('member.profile.update');
	// Route::get('schedule/clinic' , 'DashboardController@scheduleClinic')->name('member.schedule.clinic');

});



// Route::post('/member/login' , 'Admin\Auth\LoginController@login')->name('login.attempt');

Route::group(['middleware' => 'guest'], function() {
	Route::get('register/member' , 'RegisterController@memberRegisterForm')->name('member.register.form');
	Route::post('register/member/store' , 'RegisterController@memberStore')->name('member.register.store');
	Route::get('register/coach' , 'RegisterController@coachRegisterForm')->name('coach.register.form');
	// Route::view('user/login' , 'member.login')->name('user.login');
});
	Route::post('register/school/coach' , 'RegisterController@school')->name('coach.school.store');


Route::view('about' , 'pages.about' )->name('about');
Route::get('/' , 'HomeController@index')->name('home');

Route::get('/clinics' , 'ClinicController@index')->name('clinic.index');
Route::get('clinics/search' , 'ClinicController@searchCLinics')->name('clinicSearch');
Route::get('clinic/detail/{id}', 'ClinicController@detail')->name('clinic.detail');
Route::get('clinic/enrolled/detail/{id}', 'ClinicController@enrolledDetail')->name('clinic.enrolled.detail');
Route::get('clinic/enroll/{id}' , 'ClinicController@enroll')->name('enroll.index');
Route::post('clinic/enroll/update/{id}' , 'ClinicController@updateClinic')->name('clinic.enroll.update');

Route::get('contact-us' , 'ContactController@index')->name('contact');

Route::get('/pay','PaymentController@pay')->name('pay');
Route::post('/dopay/online', 'PaymentController@handleonlinepay')->name('dopay.online');

Route::get('/waiverA',function(){

    return view('waivers.waiverA');
});

Route::get('/waiverB','WaiverController@waiverB');
Route::post('/waiverB/submit','WaiverController@waiverB_send');
Route::get('/waiver/view/{id}','WaiverController@waiver_view');
Route::get('/waiverA','WaiverController@waiverA');
Route::post('/waiver/submit','WaiverController@WaiverA_submit');

Route::post('/notes/new','Member\DashboardController@notes');

Route::get('enrollments/paid', [
    'uses' => 'Coach\DashboardController@paidEnrollments',
    'as' => 'paid-enrollments'
]);

Route::get('enrollments/unpaid', [
    'uses' => 'Coach\DashboardController@unPaidEnrollments',
    'as' => 'unpaid-enrollments'
]);

Route::get('mailable', function () {
	// Mail::to(Auth::user())->send(new NewComment($ticket));
	
	$ticket = App\Ticket::find(18);
	$clinic = App\Clinic::find(7);

	// return new App\Mail\newUserRegistration();
	// return new App\Mail\clinicEnrollment($clinic);
	return new App\Mail\PasswordResetConfirmation();
});

Route::get('/test', function(Request $request) {
	return Auth::user();
	
	
	// return Auth::user()->email;
	// return 2 + 1;
	// return $request;
	// return App\Clinic::find(1)->with('clinicDetails')->get();
	// return Auth::user();
	// return view('auth.passwords.reset');
});

Route::get('coach/school/detail', 'Coach\DashboardController@getSchool');

app/School.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class School extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Admin/SchoolController.php
<?php

namespace App\Http\Controllers\Admin;

use App\School;
use App\State;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SchoolController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $schools = School::join('states', 'schools.state', '=', 'states.id')
                            ->select('schools.*', 'states.name as state_name')
                            ->get();
        return view('admin.school.index' , compact('schools'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $states = State::where('country_id', 231)->get();
        return view('admin.school.update' , compact('states'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(request(), [
                'name' => 'required',
                'city' => 'required',
                'state' => 'required',
            ]);

        $school = School::create([
                'name'         => $request->name,
                'city'          => $request->city,
                'state'         => $request->state,
                'country'       => 'US',
                'address'       => $request->address
            ]);

        return redirect()->to(route('admin.school.index'))->with(['msg' => 'School Successfully create.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\School  $school
     * @return \Illuminate\Http\Response
     */
    public function show(School $school)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\School  $school
     * @return \Illuminate\Http\Response
     */
    public function edit(School $school)
    {
        $row = $school;
        $selectedState = State::findorfail($row->state);
        // dd($row->state);
        // dd($selectedState);
        $states = State::where('country_id', 231)->get();
        return view('admin.school.update' , compact('row', 'states', 'selectedState'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\School  $school
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, School $school)
    {
        $this->validate(request(), [
                'name' => 'required',
                'city' => 'required',
                'state' => 'required',
            ]);

        $school->update([
                'name'         => $request->name,
                'city'          => $request->city,
                'state'         => $request->state,
                'country'       => 'US',
                'address'       => $request->address
            ]);

        return redirect()->to(route('admin.school.index'))->with(['msg' => 'School Successfully updated.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\School  $school
     * @return \Illuminate\Http\Response
     */
    public function destroy(School $school)
    {
        $school->delete();
        return response()->json(['status' => TRUE]);
    }
}

resources/views/admin/school/index.blade.php
@extends('admin.layouts.master')
@section('title' , 'Schools')

@section('mainContent')
{{-- @dd($__data) --}}
    <div class="content-page">
        <div class="content">

            <!-- Start Content-->
            <div class="container-fluid">
                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box">
                            <div class="page-title-right">
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                                    <li class="breadcrumb-item active">Schools</li>
                                </ol>
                            </div>
                            <h4 class="page-title">Schools</h4>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">

                                <div class="row mb-2">
                                    <div class="col-lg-8">
                                       <h4 class="header-title">Schools</h4>
                                    </div>
                                    <div class="col-lg-4">
                                        <div class="text-lg-right">
                                            <a href="{{ route('admin.school.create') }}" class="btn btn-primary waves-effect waves-light"><i class="mdi mdi-basket mr-1"></i> Add New School</a>
                                        </div>
                                    </div><!-- end col-->
                                </div>

                                <table id="scroll-horizontal-datatable" class="table w-100 nowrap">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>City</th>
                                            <th>State</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($schools as $school)
                                          <tr>
                                            <td>{{ $school->name }}</td>
                                            <td>{{ $school->city }}</td>
                                            <td>{{ $school->state_name }}</td>
                                            <td>
                                                <a href="{{ Route('admin.school.edit' , $school->id) }}" class="btn btn-info waves-effect waves-light btn-xs" title="Edit details"><i class="mdi mdi-square-edit-outline"></i></a>
                                                <a href="{{ Route('admin.school.destroy' , $school->id) }}" class="singleDelete btn btn-danger waves-effect waves-light btn-xs" title="Delete"><i class="mdi mdi-close"></i></a>
                                            </td>
                                        </tr>
                                        @empty
                                        @endforelse
                                    </tbody>
                                </table>

                            </div> <!-- end card body-->
                        </div> <!-- end card -->
                    </div><!-- end col-->
                </div>
                <!-- end row-->

            </div> <!-- container -->

        </div> <!-- content -->

       

    </div>


@stop

@section('style')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
<link href="/assets/libs/sweetalert2/sweetalert2.min.css" rel="stylesheet" type="text/css" />
@endsection

@section('script')
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
<script src="/assets/js/pages/datatables.init.js"></script>
<script src="/assets/libs/sweetalert2/sweetalert2.min.js"></script>
<script src="/assets/app/indexMaster.js"></script>
@endsection

resources/views/admin/school/update.blade.php
@extends('admin.layouts.master')

@section('title' , 'Create / update School')

@section('mainContent')
{{-- @dd($__data) --}}

@php
    if (isset($row->id)) {
       $action = Route('admin.school.update' , $row->id);
    }else{
        $action = Route('admin.school.store');
    }
@endphp

   <div class="content-page">
<div class="content">
    <!-- Start Content-->
    <div class="container-fluid">
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('admin.school.index') }}">Schools</a></li>
                                <li class="breadcrumb-item active">Create / Update School</li>
                            </ol>
                        </div>
                        <h4 class="page-title">Create / Update School</h4>
                    </div>
                </div>
            </div>
            <!-- end page title -->
        </div>
        <!-- end row -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="header-title">Fill Out Your School Information</h4>

                        <hr>

                        <div class="clearfix"></div>
                        <div class="row">
                    		<div class="col-12 text-center">
                    			<div class="form-group">
                        			<h3>General Information</h3>
                    			</div>
		                    </div>
		                </div>

                        <form  method="post" action="{{ $action }}" id="eventForm" enctype="multipart/form-data" >

					    @csrf
                        @isset ($row->id)
                            @method('PUT')
                        @endisset
                        	<div class="row">
                    			<div class="col-8 m-auto">
                                    <div class="form-row">
                                        <div class="form-group col-md-12">
                                            <label for="name" class="col-form-label">Name</label>
                                            <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" required value="{{ isset($row->name)? $row->name : old('name') }}">
                                             @error('name')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-md-12">
                                            <label for="state" class="col-form-label">State</label>
                                            {{-- <input type="text" name="state" id="state" class="form-control @error('state') is-invalid @enderror" required value="{{ isset($row->state)? $row->state : old('state') }}"> --}}
                                            <select class="form-control" name="state">
                                                @if(isset($row->state))
                                                <option value="{{ $selectedState->id }}" selected>{{ $selectedState->name }}</option>
                                                <br>
                                                @foreach($states as $s)
                                                <option value="{{ $s->id }}">{{ $s->name }}</option>
                                                @endforeach
                                                @else
                                                @foreach($states as $s)
                                                <option value="{{ $s->id }}">{{ $s->name }}</option>
                                                @endforeach
                                                @endif
                                              </select>
                                             @error('state')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-md-12">
                                            <label for="city" class="col-form-label">City</label>
                                            <input type="text" name="city" id="city" class="form-control @error('city') is-invalid @enderror" required value="{{ isset($row->city)? $row->city : old('city') }}">
                                             @error('city')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-row">
                                        <div class="form-group col-md-12">
                                            <label for="address" class="col-form-label">Address</label>
                                            <textarea name="address" id="address" class="form-control @error('address') is-invalid @enderror" cols="30" rows="5">{{ isset($row->address)? $row->address : old('address') }}</textarea>

                                             @error('address')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                    </div>
                                    
                                    <hr>

                                    <div class="form-group mb-0">
                                        <div class="custom-control custom-checkbox">
                                             <a href="{{ route('admin.team.index') }}" class="btn btn-secondary  waves-effect waves-light">Cancel</a>
                                             <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                                        </div>
                                    </div>


								</div> <!-- end card-body -->
                        	</div>
                        </form>
                	</div>
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>
        <!-- end row -->


    </div> <!-- container -->

    </div> <!-- content -->


@stop

@section('top-style')
@stop

@section('style')

@endsection

@section('script')
@endsection